-- Diseño de persistencia para la Sumativa 1 DSY2207.
-- Ejecutar en un esquema Oracle dedicado al sistema.

CREATE TABLE roles (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(80 CHAR) NOT NULL,
    description VARCHAR2(255 CHAR),
    active NUMBER(1) DEFAULT 1 NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uk_roles_name UNIQUE (name),
    CONSTRAINT ck_roles_active CHECK (active IN (0, 1))
);

CREATE TABLE usuarios (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR2(150 CHAR) NOT NULL,
    email VARCHAR2(180 CHAR) NOT NULL,
    role_id NUMBER NOT NULL,
    active NUMBER(1) DEFAULT 1 NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uk_usuarios_email UNIQUE (email),
    CONSTRAINT fk_usuarios_role FOREIGN KEY (role_id) REFERENCES roles(id),
    CONSTRAINT ck_usuarios_active CHECK (active IN (0, 1))
);

CREATE INDEX idx_usuarios_role_id ON usuarios(role_id);
