package cl.duoc.sumativa.functions;

import org.junit.jupiter.api.*;
import java.sql.*;
import java.time.Instant;
import java.util.Map;
import java.util.UUID;
import static org.junit.jupiter.api.Assertions.*;

/** H2 checks Java transactions, not Oracle PL/SQL or Azure delivery. */
class EventProcessorTest {
    Connection c;

    @BeforeEach
    void setup() throws Exception {
        c = DriverManager.getConnection("jdbc:h2:mem:" + UUID.randomUUID() + ";MODE=Oracle");
        try (Statement s = c.createStatement()) {
            s.execute(
                    "CREATE TABLE roles(id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,name VARCHAR2(80) UNIQUE,description VARCHAR2(255),active NUMBER DEFAULT 1,is_default NUMBER DEFAULT 0,deleted_at TIMESTAMP,updated_at TIMESTAMP)");
            s.execute(
                    "CREATE TABLE usuarios(id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,full_name VARCHAR2(150),email VARCHAR2(180) UNIQUE,role_id NUMBER REFERENCES roles(id),active NUMBER DEFAULT 1,default_pending NUMBER DEFAULT 0,updated_at TIMESTAMP)");
            s.execute(
                    "CREATE TABLE auditoria_eventos(event_id VARCHAR2(36) PRIMARY KEY,event_type VARCHAR2(64),subject VARCHAR2(128),occurred_at TIMESTAMP,payload CLOB)");
            s.execute("INSERT INTO roles(id,name,is_default) VALUES(100,'EFT_USUARIO',1),(200,'EDITOR',0)");
        }
    }

    @AfterEach
    void close() throws Exception {
        c.close();
    }

    boolean event(String id, String type, long entity) throws Exception {
        String raw = DomainEvent.encode(id, type, (type.startsWith("Usuarios") ? "/usuarios/" : "/roles/") + entity,
                Instant.now(), "{\"entityId\":" + entity + "}");
        return EventProcessor.process(c, DomainEvent.validate(raw));
    }

    long count(String sql) throws Exception {
        try (Statement s = c.createStatement(); ResultSet r = s.executeQuery(sql)) {
            r.next();
            return r.getLong(1);
        }
    }

    long create() {
        return ((Number) new UserRepository(c)
                .create(Map.of("fullName", "EFT Test", "email", UUID.randomUUID() + "@example.test")).get("id"))
                .longValue();
    }

    @Test
    void newUserReceivesDefaultRoleAsynchronously() throws Exception {
        long id = create();
        assertNull(new UserRepository(c).find(id).get("roleId"));
        assertTrue(event("a".repeat(32), "Usuarios.Created", id));
        assertEquals(100L, new UserRepository(c).find(id).get("roleId"));
    }

    @Test
    void duplicateDoesNotReapplyDefaultAfterManualChange() throws Exception {
        long id = create();
        event("a".repeat(32), "Usuarios.Created", id);
        new UserRepository(c).update(id, Map.of("fullName", "Test", "email", "a@example.test", "roleId", 200));
        assertFalse(event("a".repeat(32), "Usuarios.Created", id));
        assertEquals(200L, new UserRepository(c).find(id).get("roleId"));
        assertEquals(1, count("SELECT COUNT(*) FROM auditoria_eventos"));
    }

    @Test
    void deletedRoleIsHiddenThenRemovedFromAllUsers() throws Exception {
        for (int i = 0; i < 2; i++) {
            long id = create();
            new UserRepository(c).update(id, Map.of("fullName", "Test", "email", i + "@example.test", "roleId", 200));
        }
        new RoleRepository(c).delete(200);
        assertNull(new RoleRepository(c).find(200));
        assertFalse(new RoleRepository(c).exists(200));
        assertEquals(2, count("SELECT COUNT(*) FROM usuarios WHERE role_id=200"));
        event("b".repeat(32), "Roles.Deleted", 200);
        assertEquals(2, count("SELECT COUNT(*) FROM usuarios WHERE role_id IS NULL"));
        assertFalse(event("b".repeat(32), "Roles.Deleted", 200));
    }

    @Test
    void failureRollsBackAuditAndCanBeRetried() throws Exception {
        long id = create();
        try (Statement s = c.createStatement()) {
            s.execute("UPDATE roles SET active=0 WHERE id=100");
        }
        assertThrows(SQLException.class, () -> event("a".repeat(32), "Usuarios.Created", id));
        assertEquals(0, count("SELECT COUNT(*) FROM auditoria_eventos"));
        assertTrue(c.getAutoCommit());
        try (Statement s = c.createStatement()) {
            s.execute("UPDATE roles SET active=1 WHERE id=100");
        }
        assertTrue(event("a".repeat(32), "Usuarios.Created", id));
    }

    @Test
    void delayedCreationDoesNotOverwriteExplicitChoice() throws Exception {
        long id = create();
        new UserRepository(c).update(id, Map.of("fullName", "Test", "email", "later@example.test", "roleId", 200));
        event("a".repeat(32), "Usuarios.Created", id);
        assertEquals(200L, new UserRepository(c).find(id).get("roleId"));
    }

    @Test
    void liveRoleIsNotClearedByStaleDeletionEvent() throws Exception {
        long id = create();
        new UserRepository(c).update(id, Map.of("fullName", "Test", "email", "explicit@example.test", "roleId", 200));
        event("b".repeat(32), "Roles.Deleted", 200);
        assertEquals(200L, new UserRepository(c).find(id).get("roleId"));
    }

    @Test
    void creationRejectsExplicitRole() {
        assertEquals("INVALID_REQUEST",
                assertThrows(DomainException.class,
                        () -> new UserRepository(c)
                                .create(Map.of("fullName", "Test", "email", "bad@example.test", "roleId", 200)))
                        .code());
    }

    @Test
    void defaultRoleCannotBeDeleted() {
        assertEquals("ROLE_IN_USE",
                assertThrows(DomainException.class, () -> new RoleRepository(c).delete(100)).code());
    }

    @Test
    void deletedUserIsNotRecreatedByDelayedEvent() throws Exception {
        long id = create();
        new UserRepository(c).delete(id);
        event("a".repeat(32), "Usuarios.Created", id);
        assertNull(new UserRepository(c).find(id));
    }
}
