"""Usuario administrado por el sistema de Gestión de Usuarios y Roles."""
type User {
  id: ID!
  fullName: String!
  email: String!
  roleId: ID
  active: Boolean!
}

input CreateUserInput {
  fullName: String!
  email: String!
  active: Boolean = true
}

input UserInput {
  fullName: String!
  email: String!
  roleId: ID
  active: Boolean = true
}

type Query {
  users: [User!]!
  user(id: ID!): User
}

type Mutation {
  createUser(input: CreateUserInput!): User!
  updateUser(id: ID!, input: UserInput!): User!
  deleteUser(id: ID!): Boolean!
}
