package cl.duoc.sumativa.functions;

import com.fasterxml.jackson.core.type.TypeReference;
import com.microsoft.azure.functions.*;
import com.microsoft.azure.functions.annotation.*;
import java.sql.*;
import java.util.*;

public class UsuariosFunction {
  @FunctionName("UsuariosFunction")
  public HttpResponseMessage run(@HttpTrigger(name="request", methods={HttpMethod.GET,HttpMethod.POST,HttpMethod.PUT,HttpMethod.DELETE}, authLevel=AuthorizationLevel.FUNCTION, route="users/{id?}") HttpRequestMessage<Optional<String>> request, ExecutionContext context) {
    String trace=request.getHeaders().getOrDefault("x-correlation-id",UUID.randomUUID().toString());
    String id=RouteParameter.id(request.getUri(),"users");
    try(Connection connection=OracleConnection.open()) { return switch(request.getHttpMethod()) { case GET -> id==null?JsonResponses.body(request,HttpStatus.OK,list(connection),trace):one(request,connection,id,trace); case POST -> create(request,connection,trace); case PUT -> id==null?JsonResponses.error(request,HttpStatus.BAD_REQUEST,"ID_REQUIRED","El id del usuario es obligatorio.",trace):update(request,connection,id,trace); case DELETE -> id==null?JsonResponses.error(request,HttpStatus.BAD_REQUEST,"ID_REQUIRED","El id del usuario es obligatorio.",trace):delete(request,connection,id,trace); default -> JsonResponses.error(request,HttpStatus.METHOD_NOT_ALLOWED,"METHOD_NOT_ALLOWED","Método no permitido.",trace);}; }
    catch(IllegalStateException e){context.getLogger().severe(e.getMessage());return JsonResponses.error(request,HttpStatus.INTERNAL_SERVER_ERROR,"CONFIGURATION_ERROR","Configuración de base de datos incompleta.",trace);}
    catch(SQLException e){context.getLogger().severe(e.getMessage());return JsonResponses.error(request,HttpStatus.INTERNAL_SERVER_ERROR,"DATABASE_ERROR","No fue posible procesar la operación.",trace);}
  }
  private HttpResponseMessage create(HttpRequestMessage<Optional<String>> req,Connection c,String trace){try{Map<String,Object>b=JsonResponses.JSON.readValue(req.getBody().orElseThrow(),new TypeReference<>(){});if(!valid(b))return JsonResponses.error(req,HttpStatus.BAD_REQUEST,"INVALID_REQUEST","fullName, email y roleId son obligatorios.",trace);if(!roleExists(c,roleId(b)))return JsonResponses.error(req,HttpStatus.BAD_REQUEST,"ROLE_NOT_FOUND","El rol indicado no existe.",trace);try(PreparedStatement ps=c.prepareStatement("INSERT INTO usuarios(full_name,email,role_id,active) VALUES(?,?,?,?)",new String[]{"id"})){ps.setString(1,text(b,"fullName"));ps.setString(2,text(b,"email"));ps.setLong(3,roleId(b));ps.setInt(4,active(b));ps.executeUpdate();ResultSet keys=ps.getGeneratedKeys();keys.next();return JsonResponses.body(req,HttpStatus.CREATED,user(c,keys.getLong(1)),trace);}}catch(Exception e){return JsonResponses.error(req,HttpStatus.BAD_REQUEST,"INVALID_REQUEST","JSON inválido, email duplicado o datos incorrectos.",trace);}}
  private HttpResponseMessage update(HttpRequestMessage<Optional<String>> req,Connection c,String id,String trace){try{Map<String,Object>b=JsonResponses.JSON.readValue(req.getBody().orElseThrow(),new TypeReference<>(){});if(!valid(b))return JsonResponses.error(req,HttpStatus.BAD_REQUEST,"INVALID_REQUEST","fullName, email y roleId son obligatorios.",trace);if(!roleExists(c,roleId(b)))return JsonResponses.error(req,HttpStatus.BAD_REQUEST,"ROLE_NOT_FOUND","El rol indicado no existe.",trace);try(PreparedStatement ps=c.prepareStatement("UPDATE usuarios SET full_name=?,email=?,role_id=?,active=?,updated_at=SYSTIMESTAMP WHERE id=?")){ps.setString(1,text(b,"fullName"));ps.setString(2,text(b,"email"));ps.setLong(3,roleId(b));ps.setInt(4,active(b));ps.setLong(5,Long.parseLong(id));if(ps.executeUpdate()==0)return JsonResponses.error(req,HttpStatus.NOT_FOUND,"USER_NOT_FOUND","Usuario no encontrado.",trace);return JsonResponses.body(req,HttpStatus.OK,user(c,Long.parseLong(id)),trace);}}catch(Exception e){return JsonResponses.error(req,HttpStatus.BAD_REQUEST,"INVALID_REQUEST","JSON, id o datos inválidos.",trace);}}
  private HttpResponseMessage delete(HttpRequestMessage<?> req,Connection c,String id,String trace){try(PreparedStatement ps=c.prepareStatement("DELETE FROM usuarios WHERE id=?")){ps.setLong(1,Long.parseLong(id));if(ps.executeUpdate()==0)return JsonResponses.error(req,HttpStatus.NOT_FOUND,"USER_NOT_FOUND","Usuario no encontrado.",trace);return req.createResponseBuilder(HttpStatus.NO_CONTENT).header("X-Correlation-Id",trace).build();}catch(Exception e){return JsonResponses.error(req,HttpStatus.BAD_REQUEST,"INVALID_ID","Id inválido.",trace);}}
  private HttpResponseMessage one(HttpRequestMessage<?> req,Connection c,String id,String trace)throws SQLException{try{Map<String,Object>value=user(c,Long.parseLong(id));return value==null?JsonResponses.error(req,HttpStatus.NOT_FOUND,"USER_NOT_FOUND","Usuario no encontrado.",trace):JsonResponses.body(req,HttpStatus.OK,value,trace);}catch(NumberFormatException e){return JsonResponses.error(req,HttpStatus.BAD_REQUEST,"INVALID_ID","Id inválido.",trace);}}
  private List<Map<String,Object>> list(Connection c)throws SQLException{List<Map<String,Object>>values=new ArrayList<>();try(Statement st=c.createStatement();ResultSet rs=st.executeQuery("SELECT id,full_name,email,role_id,active FROM usuarios ORDER BY id")){while(rs.next())values.add(map(rs));}return values;}
  private Map<String,Object> user(Connection c,long id)throws SQLException{try(PreparedStatement ps=c.prepareStatement("SELECT id,full_name,email,role_id,active FROM usuarios WHERE id=?")){ps.setLong(1,id);ResultSet rs=ps.executeQuery();return rs.next()?map(rs):null;}}
  private boolean roleExists(Connection c,long id)throws SQLException{try(PreparedStatement ps=c.prepareStatement("SELECT 1 FROM roles WHERE id=?")){ps.setLong(1,id);return ps.executeQuery().next();}}
  private Map<String,Object> map(ResultSet rs)throws SQLException{return Map.of("id",rs.getLong("id"),"fullName",rs.getString("full_name"),"email",rs.getString("email"),"roleId",rs.getLong("role_id"),"active",rs.getInt("active")==1);}
  private boolean valid(Map<String,Object>b){try{return text(b,"fullName")!=null&&text(b,"email")!=null&&roleId(b)>0;}catch(Exception e){return false;}}
  private String text(Map<String,Object>b,String key){Object v=b.get(key);return v==null||v.toString().isBlank()?null:v.toString();}
  private long roleId(Map<String,Object>b){return Long.parseLong(String.valueOf(b.get("roleId")));}
  private int active(Map<String,Object>b){return Boolean.FALSE.equals(b.get("active"))?0:1;}
}
