spring.application.name=usuarios-roles-bff
server.port=${SERVER_PORT:8080}
management.endpoints.web.exposure.include=health,info
functions.users-url=${USERS_FUNCTION_URL:http://localhost:7071/api/users}
functions.users-key=${USERS_FUNCTION_KEY:}
functions.roles-url=${ROLES_FUNCTION_URL:http://localhost:7071/api/roles}
functions.roles-key=${ROLES_FUNCTION_KEY:}
